Basic portable implementation

diff --git a/protonlaunch b/protonlaunch
--- a/protonlaunch
+++ b/protonlaunch
@@ -40,24 +40,24 @@ PROGRAM_NAME="$(basename "$(echo "${0}")")"
 
 
 # Show message logs
-function pl_info() {
+pl_info() {
     echo "${pl_bold}${pl_blue}${PROGRAM_NAME}:${pl_normal} ${1}" >&1
 }
 
 # Show a warning message
-function pl_warning() {
+pl_warning() {
     echo "${pl_bold}${pl_yellow}${PROGRAM_NAME}: Warning:${pl_normal} ${1}" >&1
 }
 
 # Raise an error and terminate the application
-function pl_error() {
+pl_error() {
     echo "${pl_bold}${pl_red}${PROGRAM_NAME}: Error:${pl_normal} ${1}" >&2
     exit 1
 }
 
 
 # Show a usage message
-function pl_usage() {
+pl_usage() {
     echo "Usage: ${0} [option] program [arguments...]"
     echo
     echo "Options:"
@@ -114,7 +114,7 @@ function pl_usage() {
 
 
 # Show a version message
-function pl_version() {
+pl_version() {
     echo "ProtonLaunch version ${VERSION}"
     echo "Protonlaunch is licensed under BSD 3-Clause License <https://opensource.org/licenses/BSD-3-Clause>"
 
@@ -125,7 +125,7 @@ function pl_version() {
 
 
 # Set colors if supported
-function pl_set_color() {
+pl_set_color() {
     ncolors="$(tput colors)"
     if [ -z ${PL_NO_COLORS} ] && [ -t 1 ] && [ -n ${ncolors} ] && [ $(tput colors) -ge 8 ]; then
         export pl_bold="$(tput bold)"
@@ -143,9 +143,22 @@ function pl_set_color() {
     fi
 }
 
+# Set legacy support variables
+pl_set_legacy_support() {
+    if [ ! -z ${_STEAM_PATH} ]; then
+        pl_warning "_STEAM_PATH is deprecate, you should use PL_STEAM_PATH"
+        PL_STEAM_PATH="${_STEAM_PATH}"
+    fi
+
+    if [ ! -z ${_STEAM_LIBRARY_PATH} ]; then
+        pl_warning "_STEAM_LIBRARY_PATH is deprecate, you should use PL_LIBRARY_PATH"
+        pl_add_library_path "${_STEAM_LIBRARY_PATH}"
+    fi
+}
+
 
 # Find Steam installation path
-function pl_get_steam_path() {
+pl_get_steam_path() {
     if [ -z ${STEAM_COMPAT_CLIENT_INSTALL_PATH} ]; then
 
         if [ ! -z ${PL_STEAM_PATH} ]; then
@@ -183,7 +196,7 @@ function pl_get_steam_path() {
 
 
 # Add a path to the steam library paths
-function pl_add_library_path() {
+pl_add_library_path() {
     if [ -z ${PL_LIBRARY_PATH} ]; then
         export PL_LIBRARY_PATH="${1}"
     else
@@ -193,14 +206,14 @@ function pl_add_library_path() {
 
 
 # Find Steam library paths
-function pl_get_steam_library() {
+pl_get_steam_library() {
     if [ -f "${STEAM_COMPAT_CLIENT_INSTALL_PATH}/config/libraryfolders.vdf" ]; then
         pl_paths="$(grep -i path "${STEAM_COMPAT_CLIENT_INSTALL_PATH}/config/libraryfolders.vdf")"
-        while read pl_path
+        for pl_path in ${pl_paths}; do
             if [ -d "${pl_path}/stemapps/common" ]; then
                 pl_add_library_path "${pl_path}"
             fi
-        done <<< "${pl_paths}"
+        done
     fi
 
     if [ -z "${PL_LIBRARY_PATH}" ]; then
@@ -214,7 +227,7 @@ function pl_get_steam_library() {
 
 
 # Add proton to proton list
-function pl_add_proton_list() {
+pl_add_proton_list() {
     if [ -z ${PL_PROTON_LIST} ]; then
         export PL_PROTON_LIST="${1}"
     else
@@ -224,25 +237,30 @@ function pl_add_proton_list() {
 
 
 # Get all proton versions
-function pl_get_proton_list() {
-    while read -rd: pl_path; do
+pl_get_proton_list() {
+    old_ifs="${IFS}"
+    IFS=":"
+    for pl_path in ${PL_LIBRARY_PATH}; do
         library_path="${pl_path}/steamapps/common"
         for proton in ${library_path}/*; do
             if echo ${proton} | grep -i proton && [ -f "${proton}/proton" ]; then
                 pl_add_proton_list "${proton}"
             fi
         done
-    done <<< "${PL_LIBRARY_PATH}"
+    done
+    IFS="${old_ifs}"
 }
 
 
 # Get proton
-function pl_get_proton() {
+pl_get_proton() {
     if [ -z ${PL_PROTON_LIST} ]; then
         pl_error "no Proton installation found, make sure you've installed Proton trough Steam"
     fi
 
-    while read -rd: proton; do
+    old_ifs="${IFS}"
+    IFS=":"
+    for proton in ${PL_PROTON_LIST}; do
         name="$(basename ${proton})"
         if [ -z ${PL_PROTON_VERSION} ]; then
             if [ "${name}" != "Proton - Experimental" ] != [ -z ${pl_proton_path} ]; then
@@ -253,7 +271,8 @@ function pl_get_proton() {
                 export pl_proton_path="${proton}/proton"
             fi
         fi
-    done <<< "${PL_PROTON_LIST}"
+    done
+    IFS="${old_ifs}"
 
     if [ -z ${pl_proton_path} ]; then
         pl_error "Unable to find Proton installation of '${PL_PROTON_VERSION}'"
@@ -261,7 +280,7 @@ function pl_get_proton() {
 }
 
 # Get prefix path
-function pl_get_prefix() {
+pl_get_prefix() {
     if [ -z ${STEAM_COMPAT_DATA_PATH} ]; then
         if [ ! -z "${WINEPREFIX}" ]; then
             pl_warning "is not recommended to use WINEPREFIX. Use PROTONPREFIX instead"
@@ -280,7 +299,7 @@ function pl_get_prefix() {
 
 
 # Bootstrap prefix
-function pl_bootstrap() {
+pl_bootstrap() {
     if [ ! -d "${1}/pfx/drive_c" ]; then
         pl_info "Bootstrapping '${1}'"
         "${proton}" run wineboot
@@ -289,7 +308,7 @@ function pl_bootstrap() {
 
 
 # Run a program
-function pl_run() {
+pl_run() {
     command="${1}"
     shift
     params=${@}
@@ -306,7 +325,7 @@ function pl_run() {
 
 
 # Enable NVAPI / DLSS
-function pl_nvapi() {
+pl_nvapi() {
     if [ -z "${PROTON_ENABLE_NVAPI}" ]; then
         if [ "${_NVAPI}" == "1" ] || [ "${_DLSS}" == "1" ]; then
             pl_info "NVAPI Enabled"
@@ -317,7 +336,7 @@ function pl_nvapi() {
 
 
 # Enable RayTracing
-function pl_dxr() {
+pl_dxr() {
     if [ "${_DXR}" == "1" ]; then
         pl_info "DirectX RayTracing Enabled"
         if [ -z "${VKD3D_CONFIG}" ]; then
@@ -330,7 +349,7 @@ function pl_dxr() {
 
 
 # Enable NVIDIA RayTracing
-function pl_rtx() {
+pl_rtx() {
     if [ "${_RTX}" == "1" ]; then
         export _NVAPI="1"
         export _DXR="1"
@@ -341,7 +360,7 @@ function pl_rtx() {
 
 
 # Enable frame capping
-function pl_framecap() {
+pl_framecap() {
     if [ ! -z "${_FRAMECAP}" ] && [ -z "${DXVK_FRAME_RATE}" ]; then
         pl_info "Framerate capped at ${_FRAMECAP} FPS"
         export DXVK_FRAME_RATE="${_FRAMECAP}"
@@ -350,7 +369,7 @@ function pl_framecap() {
 
 
 # Enable AMD FSR
-function pl_fsr() {
+pl_fsr() {
     if [ "${_FSR}" == "1" ] && [ -z "${WINE_FULLSCREEN_FSR}" ]; then
         pl_info "AMD FSR Enabled"
         export WINE_FULLSCREEN_FSR=1
@@ -358,54 +377,56 @@ function pl_fsr() {
 }
 
 
-# Manage launch options
-if [ -z "${1}" ]; then
-    pl_error "Expecting a program name or aregument, try --help"
-fi
 
-case ${1} in
-    "-h") pl_usage; exit 0;;
-    "--help") pl_usage; exit 0;;
-    "-v") pl_version; exit 0;;
-    "--version") pl_version; exit 0;;
-esac
 
-# Get variables
-if [ -z ${STEAM_COMPAT_CLIENT_INSTALL_PATH} ]; then
-    pl_get_steam_path
-fi
-pl_info "Steam installation path is '${STEAM_COMPAT_CLIENT_INSTALL_PATH}'"
+# # Manage launch options
+# if [ -z "${1}" ]; then
+#     pl_error "Expecting a program name or aregument, try --help"
+# fi
 
-if [ -z ${_STEAM_LIBRARY_PATH} ]; then
-    pl_get_steam_library
-fi
-pl_info "Steam library path is '${_STEAM_LIBRARY_PATH}'"
+# case ${1} in
+#     "-h") pl_usage; exit 0;;
+#     "--help") pl_usage; exit 0;;
+#     "-v") pl_version; exit 0;;
+#     "--version") pl_version; exit 0;;
+# esac
 
-if [ -z "${_PROTON_VERSION}" ]; then
-    pl_get_proton_version
-fi
-pl_info "Proton version '${_PROTON_VERSION}'"
+# # Get variables
+# if [ -z ${STEAM_COMPAT_CLIENT_INSTALL_PATH} ]; then
+#     pl_get_steam_path
+# fi
+# pl_info "Steam installation path is '${STEAM_COMPAT_CLIENT_INSTALL_PATH}'"
 
-pl_get_proton_path
+# if [ -z ${_STEAM_LIBRARY_PATH} ]; then
+#     pl_get_steam_library
+# fi
+# pl_info "Steam library path is '${_STEAM_LIBRARY_PATH}'"
 
-pl_get_prefix
-pl_info "Prefix '${STEAM_COMPAT_DATA_PATH}'"
+# if [ -z "${_PROTON_VERSION}" ]; then
+#     pl_get_proton_version
+# fi
+# pl_info "Proton version '${_PROTON_VERSION}'"
 
-# Create and bootstrap prefix
-if ! mkdir -pv "${STEAM_COMPAT_DATA_PATH}"; then
-    pl_error "Failed to create prefix '${STEAM_COMPAT_DATA_PATH}'"
-fi
-if ! pl_bootstrap "${STEAM_COMPAT_DATA_PATH}"; then
-    pl_error "Failed to bootstrap '${STEAM_COMPAT_DATA_PATH}'"
-fi
+# pl_get_proton_path
 
-pl_mangohud
-pl_gamemode
-pl_nvapi
-pl_dxr
-pl_rtx
-pl_framecap
-pl_fsr
+# pl_get_prefix
+# pl_info "Prefix '${STEAM_COMPAT_DATA_PATH}'"
 
-# Run proton
-pl_run "${@}"
+# # Create and bootstrap prefix
+# if ! mkdir -pv "${STEAM_COMPAT_DATA_PATH}"; then
+#     pl_error "Failed to create prefix '${STEAM_COMPAT_DATA_PATH}'"
+# fi
+# if ! pl_bootstrap "${STEAM_COMPAT_DATA_PATH}"; then
+#     pl_error "Failed to bootstrap '${STEAM_COMPAT_DATA_PATH}'"
+# fi
+
+# pl_mangohud
+# pl_gamemode
+# pl_nvapi
+# pl_dxr
+# pl_rtx
+# pl_framecap
+# pl_fsr
+
+# # Run proton
+# pl_run "${@}"
