Lauching wine applications with proton

diff --git a/protonlaunch b/protonlaunch
--- a/protonlaunch
+++ b/protonlaunch
@@ -37,13 +37,15 @@ function error() {
 }
 
 # Finding Steam
-if [ -z "${_STEAM_PATH}" ] && [ -z ${STEAM_COMPAT_CLIENT_INSTALL_PATH} ]; then
-    if [ -e "${HOME}/.local/share/Steam/steam.sh" ]; then
-        STEAM_COMPAT_CLIENT_INSTALL_PATH="${HOME}/.local/share/Steam"
+if [ -z ${STEAM_COMPAT_CLIENT_INSTALL_PATH} ]; then
+    if [ -e "${_STEAM_PATH}/steam.sh" ]; then
+        export STEAM_COMPAT_CLIENT_INSTALL_PATH="${_STEAM_PATH}"
+    elif [ -e "${HOME}/.local/share/Steam/steam.sh" ]; then
+        export STEAM_COMPAT_CLIENT_INSTALL_PATH="${HOME}/.local/share/Steam"
     elif [ -h "${HOME}/.steam/steam" ]; then
-        STEAM_COMPAT_CLIENT_INSTALL_PATH="$(readlink ${HOME}/.steam/steam)"
+        export STEAM_COMPAT_CLIENT_INSTALL_PATH="$(readlink ${HOME}/.steam/steam)"
     else
-        error "Unable to find Steam path, please set STEAM_PATH"
+        error "Unable to find Steam path, please set _STEAM_PATH"
     fi
     info "Steam found at '${STEAM_COMPAT_CLIENT_INSTALL_PATH}'"
 fi
@@ -52,19 +54,46 @@ fi
 if [ -z "${_STEAM_LIBRARY_PATH}" ]; then
     if [ -d "${STEAM_COMPAT_CLIENT_INSTALL_PATH}/steamapps/common" ]; then
         info "Using '${STEAM_COMPAT_CLIENT_INSTALL_PATH}' as library path"
-        STEAM_LIBRARY_PATH="${STEAM_COMPAT_CLIENT_INSTALL_PATH}"
+        _STEAM_LIBRARY_PATH="${STEAM_COMPAT_CLIENT_INSTALL_PATH}"
     else
-        error "Unable to find Steam library, make sure that Proton is installed and set STEAM_LIBRARY_PATH if necessary"
+        error "Unable to find Steam library, make sure that Proton is installed and set _STEAM_LIBRARY_PATH if necessary"
     fi
 fi
 
-# # Set WINEPREFIX or PROTONPREFIX
-# if [ -z "${STEAM_COMPAT_DATA_PATH}" ]; then
-#     if [ ! -z "${WINEPREFIX}" ]; then
-#         STEAM_COMPAT_DATA_PATH="${WINEPREFIX}"
-#     elif [ ! -z "${SPROTONPREFIX}" ]; then
-#         STEAM_COMPAT_DATA_PATH="${WINEPREFIX}"
-#     else
-#         STEAM_COMPAT_DATA_PATH="${HOME}/.proton"
-#     fi
-# fi
+# Getting Proton version
+if [ -z "${_PROTON_VERSION}" ]; then
+    if ! ls "${_STEAM_LIBRARY_PATH}/steamapps/common" | grep -i proton 2>&1 > /dev/null; then
+        error "Unable to find Proton on '${_STEAM_LIBRARY_PATH}', make sure proton is installed and set _PROTON_VERSION if necessary"
+    fi
+    _PROTON_VERSION="$(ls "${_STEAM_LIBRARY_PATH}/steamapps/common" | grep -i proton | head -n 1)"
+    info "Using proton '${_PROTON_VERSION}'"
+fi
+
+# Checking for proton
+if [ -e "${_STEAM_LIBRARY_PATH}/steamapps/common/${_PROTON_VERSION}/proton" ]; then
+    proton="${_STEAM_LIBRARY_PATH}/steamapps/common/${_PROTON_VERSION}/proton"
+else
+    error "Unable to find Proton installation on '${_STEAM_LIBRARY_PATH}/steamapps/common/${_PROTON_VERSION}'"
+fi
+
+# Set WINEPREFIX or PROTONPREFIX
+if [ -z "${STEAM_COMPAT_DATA_PATH}" ]; then
+    if [ ! -z "${WINEPREFIX}" ]; then
+        export STEAM_COMPAT_DATA_PATH="${WINEPREFIX}"
+    elif [ ! -z "${PROTONPREFIX}" ]; then
+        export STEAM_COMPAT_DATA_PATH="${PROTONPREFIX}"
+    else
+        info "Using prefix '${HOME}/.proton'"
+        export STEAM_COMPAT_DATA_PATH="${HOME}/.proton"
+    fi
+fi
+
+if [ ! -d "${STEAM_COMPAT_DATA_PATH}" ]; then
+    info "Creating '${STEAM_COMPAT_DATA_PATH}'"
+    mkdir "${STEAM_COMPAT_DATA_PATH}"
+fi
+
+# Launch proton
+command="${*}"
+info "Starting Steam Proton with command '${command}'"
+"${proton}" run "${command}"
